export const TRIGGER_LOGIN = "TRIGGER_LOGIN";
export const CHAT_CONNECTED = "CHAT_CONNECTED";
export const CHAT_DISCONNECTED = "CHAT_DISCONNECTED";
export const CHAT_ERROR = "CHAT_ERROR";
export const ON_MESSAGE = "ON_MESSAGE";

